configuration:  
  projectName: cardclient

server:
  port: 8000

message:
  greeting: wszystko ok

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

spring:
  redis:
    host: localhost
    port: 6379
